name: "Setup"
description: "Setup Ruby, Node and install yarn packages"

runs:
  using: "composite"
  steps:
    - name: Configure Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Configure Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.0

    - name: Install yarn packages
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
