require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'target/**/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
